### ISSUE TITLE
Nav Bar not removed

### ISSUE THREAD

**Issue by dj95** [Linux-statt-Windows/lsw-android-app#1]
This is the error my xperia go reports, when it tries to remove the nav bar. 

```
05-20 10:08:06.324    9971-9971/io.lsw.dev.linuxstattwindows E/Web Console﹕ Uncaught TypeError: Object #<HTMLDivElement> has no method 'remove' at null:1
```

**Comment by rbeer** [comment]
" Javascript won't let an element commit suicide, but it does permit infanticide... " - ^_^
(http://stackoverflow.com/questions/3387427/remove-element-by-id#comment3521845_3387427)

I'd be cautious with ChildNode.remove(), as it still has some issues in IE/Safari mobile - and aparently some android code, too)
(https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Browser_compatibility)

#<HTMLDivElement>.parentNode.removeChild(#<HTMLDivElement>); is safe.
(https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild#Example)

**Comment by dj95** [comment]
It works! Thanks :)
